// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/audit/v1beta/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryAuditorsRequest is request type for the Query/Orders RPC method
type QueryAuditorsRequest struct {
	Filters    AuditFilters       `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuditorsRequest) Reset()         { *m = QueryAuditorsRequest{} }
func (m *QueryAuditorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorsRequest) ProtoMessage()    {}
func (*QueryAuditorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c495d166414b11, []int{0}
}
func (m *QueryAuditorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorsRequest.Merge(m, src)
}
func (m *QueryAuditorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorsRequest proto.InternalMessageInfo

func (m *QueryAuditorsRequest) GetFilters() AuditFilters {
	if m != nil {
		return m.Filters
	}
	return AuditFilters{}
}

func (m *QueryAuditorsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAuditorsResponse is response type for the Query/Orders RPC method
type QueryAuditorsResponse struct {
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuditorsResponse) Reset()         { *m = QueryAuditorsResponse{} }
func (m *QueryAuditorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorsResponse) ProtoMessage()    {}
func (*QueryAuditorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c495d166414b11, []int{1}
}
func (m *QueryAuditorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorsResponse.Merge(m, src)
}
func (m *QueryAuditorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorsResponse proto.InternalMessageInfo

func (m *QueryAuditorsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// OrderFilters defines flags for order list filter
type AuditFilters struct {
}

func (m *AuditFilters) Reset()         { *m = AuditFilters{} }
func (m *AuditFilters) String() string { return proto.CompactTextString(m) }
func (*AuditFilters) ProtoMessage()    {}
func (*AuditFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c495d166414b11, []int{2}
}
func (m *AuditFilters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuditFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuditFilters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuditFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditFilters.Merge(m, src)
}
func (m *AuditFilters) XXX_Size() int {
	return m.Size()
}
func (m *AuditFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditFilters.DiscardUnknown(m)
}

var xxx_messageInfo_AuditFilters proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryAuditorsRequest)(nil), "akash.audit.v1beta1.QueryAuditorsRequest")
	proto.RegisterType((*QueryAuditorsResponse)(nil), "akash.audit.v1beta1.QueryAuditorsResponse")
	proto.RegisterType((*AuditFilters)(nil), "akash.audit.v1beta1.AuditFilters")
}

func init() { proto.RegisterFile("akash/audit/v1beta/query.proto", fileDescriptor_78c495d166414b11) }

var fileDescriptor_78c495d166414b11 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3d, 0x4f, 0xfa, 0x40,
	0x1c, 0xc7, 0x7b, 0x84, 0xff, 0x43, 0x4e, 0xa7, 0x8a, 0x09, 0x21, 0xa6, 0x68, 0xe3, 0x23, 0xc3,
	0x5d, 0x8a, 0x9b, 0x8b, 0x81, 0x01, 0x57, 0x65, 0x74, 0xf2, 0x8a, 0x67, 0x69, 0x28, 0xfd, 0x95,
	0xde, 0x95, 0xc8, 0xea, 0x6e, 0x62, 0xe2, 0xe0, 0xaa, 0xef, 0x86, 0x91, 0xc4, 0xc5, 0xc9, 0x18,
	0x70, 0xf0, 0x65, 0x98, 0xde, 0x95, 0x88, 0xda, 0x44, 0xb7, 0x36, 0xdf, 0x87, 0xcf, 0xf7, 0xae,
	0xc5, 0x16, 0xeb, 0x31, 0xd1, 0xa5, 0x2c, 0x39, 0xf7, 0x25, 0x1d, 0x3a, 0x2e, 0x97, 0x8c, 0x0e,
	0x12, 0x1e, 0x8f, 0x48, 0x14, 0x83, 0x04, 0x73, 0x45, 0xe9, 0x44, 0xe9, 0x44, 0xeb, 0x4e, 0xa5,
	0xe4, 0x81, 0x07, 0x4a, 0xa7, 0xe9, 0x93, 0xb6, 0x56, 0xd6, 0x3c, 0x00, 0x2f, 0xe0, 0x94, 0x45,
	0x3e, 0x65, 0x61, 0x08, 0x92, 0x49, 0x1f, 0x42, 0x91, 0xa9, 0xb5, 0x0e, 0x88, 0x3e, 0x08, 0xea,
	0x32, 0xc1, 0x35, 0x21, 0xc3, 0x39, 0x34, 0x62, 0x9e, 0x1f, 0x2a, 0xb3, 0xf6, 0xda, 0x0f, 0x08,
	0x97, 0x4e, 0x52, 0x4b, 0x23, 0xc5, 0x42, 0x2c, 0xda, 0x7c, 0x90, 0x70, 0x21, 0xcd, 0x06, 0xfe,
	0x77, 0xe1, 0x07, 0x92, 0xc7, 0xa2, 0x8c, 0xd6, 0xd1, 0xee, 0x52, 0x7d, 0x83, 0xe4, 0xec, 0x23,
	0x2a, 0xd6, 0xd2, 0xc6, 0x66, 0x71, 0xfc, 0x5c, 0x35, 0xda, 0xf3, 0x9c, 0xd9, 0xc2, 0xf8, 0x83,
	0x57, 0x2e, 0xa8, 0x96, 0x6d, 0xa2, 0xc7, 0x91, 0x74, 0x1c, 0xd1, 0xc7, 0x9f, 0x77, 0x1d, 0x33,
	0x8f, 0x67, 0xf8, 0xf6, 0x42, 0xd2, 0x3e, 0xc3, 0xab, 0x5f, 0x26, 0x8a, 0x08, 0x42, 0xc1, 0xcd,
	0xa3, 0x1c, 0xc0, 0xce, 0x8f, 0x00, 0x1d, 0xfe, 0x44, 0x28, 0xe1, 0xe5, 0xc5, 0x83, 0x1c, 0x14,
	0xdf, 0xee, 0xab, 0x46, 0xfd, 0x0e, 0xe1, 0x3f, 0x0a, 0x6c, 0x5e, 0x23, 0xfc, 0x7f, 0x4e, 0x37,
	0xf7, 0x72, 0x2f, 0x22, 0xef, 0x12, 0x2b, 0xb5, 0xdf, 0x58, 0xf5, 0x1e, 0xbb, 0x76, 0xf5, 0xf8,
	0x7a, 0x5b, 0xd8, 0x34, 0x6d, 0xfa, 0xfd, 0x3f, 0x71, 0xf4, 0x1b, 0xc4, 0x82, 0x06, 0xbe, 0x90,
	0xcd, 0xc3, 0xf1, 0xd4, 0x42, 0x93, 0xa9, 0x85, 0x5e, 0xa6, 0x16, 0xba, 0x99, 0x59, 0xc6, 0x64,
	0x66, 0x19, 0x4f, 0x33, 0xcb, 0x38, 0xdd, 0xf2, 0x7c, 0xd9, 0x4d, 0x5c, 0xd2, 0x81, 0x3e, 0x85,
	0x61, 0xdc, 0x09, 0x7a, 0x59, 0xdd, 0x65, 0x56, 0x28, 0x47, 0x11, 0x17, 0xee, 0x5f, 0xf5, 0xf5,
	0xf7, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x39, 0x10, 0x24, 0x94, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Auditors(ctx context.Context, in *QueryAuditorsRequest, opts ...grpc.CallOption) (*QueryAuditorsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Auditors(ctx context.Context, in *QueryAuditorsRequest, opts ...grpc.CallOption) (*QueryAuditorsResponse, error) {
	out := new(QueryAuditorsResponse)
	err := c.cc.Invoke(ctx, "/akash.audit.v1beta1.Query/Auditors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Auditors(context.Context, *QueryAuditorsRequest) (*QueryAuditorsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Auditors(ctx context.Context, req *QueryAuditorsRequest) (*QueryAuditorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auditors not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Auditors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Auditors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.audit.v1beta1.Query/Auditors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Auditors(ctx, req.(*QueryAuditorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "akash.audit.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auditors",
			Handler:    _Query_Auditors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "akash/audit/v1beta/query.proto",
}

func (m *QueryAuditorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Filters.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAuditorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *AuditFilters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuditFilters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuditFilters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAuditorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Filters.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAuditorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *AuditFilters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAuditorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Filters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuditFilters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuditFilters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuditFilters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
